name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "train_pca.csv"
  TARGET_VAR: "Credit_Score"
  PROJECT_PATH: "Modul 4 - Serving Model dengan Gaya/Cinta Segitiga Latihan Integrasi/MLproject"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # 4️⃣ Jalankan MLflow Project
      - name: Run MLflow Project
        run: |
          cd "$PROJECT_PATH"
          mlflow run . --env-manager=local

      # 5️⃣ Ambil run_id terakhir
      - name: Get latest MLflow run_id
        id: get_run
        run: |
          cd "$PROJECT_PATH"
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "Latest run_id: $RUN_ID"

      # 6️⃣ Build Docker Model dari run_id sebelumnya
      - name: Build Docker Model
        run: |
          cd "$PROJECT_PATH"
          echo "Building model from run ID: ${{ steps.get_run.outputs.run_id }}"
          mlflow models build-docker --model-uri "runs:/${{ steps.get_run.outputs.run_id }}/model" --name "cc"

      # 7️⃣ Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 8️⃣ Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest

      # 9️⃣ Push Docker Image ke Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
